/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package club.manager.gui.view;

/**
 *
 * @author Johannes
 */
public class Search extends javax.swing.JPanel {

   
    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        searchCoachPanel = new javax.swing.JPanel();
        searchTeams = new javax.swing.JLabel();
        teamCombo = new javax.swing.JComboBox();
        listMembersPanel = new javax.swing.JPanel();
        listMembersLabel = new javax.swing.JLabel();
        listByPnrBtn = new javax.swing.JButton();
        listBySurnameBtn = new javax.swing.JButton();
        listTeamsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        listTeamsCombo = new javax.swing.JComboBox();
        changeMembersPanel = new javax.swing.JPanel();
        searchMember = new javax.swing.JLabel();
        surnameText = new javax.swing.JTextField();
        pnrText = new javax.swing.JTextField();
        surnameLabel = new javax.swing.JLabel();
        pnrLabel = new javax.swing.JLabel();
        orLabel = new javax.swing.JLabel();

        searchTeams.setFont(new java.awt.Font("Gautami", 1, 14)); // NOI18N
        searchTeams.setText("Search for the coach of a team");

        teamCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout searchCoachPanelLayout = new javax.swing.GroupLayout(searchCoachPanel);
        searchCoachPanel.setLayout(searchCoachPanelLayout);
        searchCoachPanelLayout.setHorizontalGroup(
            searchCoachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCoachPanelLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(searchTeams)
                .addGap(109, 109, 109))
            .addGroup(searchCoachPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(teamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchCoachPanelLayout.setVerticalGroup(
            searchCoachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCoachPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTeams)
                .addGap(66, 66, 66)
                .addComponent(teamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search coach", searchCoachPanel);

        listMembersLabel.setFont(new java.awt.Font("Gautami", 1, 14)); // NOI18N
        listMembersLabel.setText("List all Members");

        listByPnrBtn.setText("List by Person Number");
        buttonGroup1.add(listByPnrBtn);
        listByPnrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listByPnrBtnActionPerformed(evt);
            }
        });

        listBySurnameBtn.setText("List by surname");
        buttonGroup1.add(listBySurnameBtn);

        javax.swing.GroupLayout listMembersPanelLayout = new javax.swing.GroupLayout(listMembersPanel);
        listMembersPanel.setLayout(listMembersPanelLayout);
        listMembersPanelLayout.setHorizontalGroup(
            listMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listMembersPanelLayout.createSequentialGroup()
                .addGroup(listMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listMembersPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(listMembersLabel))
                    .addGroup(listMembersPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(listByPnrBtn)
                        .addGap(41, 41, 41)
                        .addComponent(listBySurnameBtn)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        listMembersPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {listByPnrBtn, listBySurnameBtn});

        listMembersPanelLayout.setVerticalGroup(
            listMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listMembersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listMembersLabel)
                .addGap(73, 73, 73)
                .addGroup(listMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(listByPnrBtn)
                    .addComponent(listBySurnameBtn))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("List members", listMembersPanel);

        jLabel4.setFont(new java.awt.Font("Gautami", 1, 14)); // NOI18N
        jLabel4.setText("List information about a team");

        listTeamsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout listTeamsPanelLayout = new javax.swing.GroupLayout(listTeamsPanel);
        listTeamsPanel.setLayout(listTeamsPanelLayout);
        listTeamsPanelLayout.setHorizontalGroup(
            listTeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listTeamsPanelLayout.createSequentialGroup()
                .addGroup(listTeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listTeamsPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel4))
                    .addGroup(listTeamsPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(listTeamsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        listTeamsPanelLayout.setVerticalGroup(
            listTeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listTeamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(69, 69, 69)
                .addComponent(listTeamsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("List teams", listTeamsPanel);

        searchMember.setFont(new java.awt.Font("Gautami", 1, 14)); // NOI18N
        searchMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchMember.setText("Search for a member");

        surnameText.setText("Enter a surname...");
        surnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextActionPerformed(evt);
            }
        });

        pnrText.setText("Enter a person number...");
        pnrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnrTextActionPerformed(evt);
            }
        });

        surnameLabel.setText("Surname:");

        pnrLabel.setText("Person Number:");

        orLabel.setText("or");

        javax.swing.GroupLayout changeMembersPanelLayout = new javax.swing.GroupLayout(changeMembersPanel);
        changeMembersPanel.setLayout(changeMembersPanelLayout);
        changeMembersPanelLayout.setHorizontalGroup(
            changeMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeMembersPanelLayout.createSequentialGroup()
                .addGroup(changeMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orLabel)
                    .addGroup(changeMembersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(changeMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnrLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(surnameLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changeMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchMember, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameText)
                    .addComponent(pnrText, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        changeMembersPanelLayout.setVerticalGroup(
            changeMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeMembersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchMember)
                .addGap(42, 42, 42)
                .addGroup(changeMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameLabel))
                .addGap(9, 9, 9)
                .addComponent(orLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changeMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnrText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnrLabel))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Members", changeMembersPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void surnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextActionPerformed

    private void pnrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnrTextActionPerformed

    private void listByPnrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listByPnrBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listByPnrBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel changeMembersPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton listByPnrBtn;
    private javax.swing.JButton listBySurnameBtn;
    private javax.swing.JLabel listMembersLabel;
    private javax.swing.JPanel listMembersPanel;
    private javax.swing.JComboBox listTeamsCombo;
    private javax.swing.JPanel listTeamsPanel;
    private javax.swing.JLabel orLabel;
    private javax.swing.JLabel pnrLabel;
    private javax.swing.JTextField pnrText;
    private javax.swing.JPanel searchCoachPanel;
    private javax.swing.JLabel searchMember;
    private javax.swing.JLabel searchTeams;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameText;
    private javax.swing.JComboBox teamCombo;
    // End of variables declaration//GEN-END:variables
}
